"""empty message

Revision ID: 8023ba9ac0f2
Revises: a5e7c6c2b04f
Create Date: 2020-07-11 11:06:02.940575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8023ba9ac0f2'
down_revision = 'a5e7c6c2b04f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=False)
    op.add_column('pitch', sa.Column('category_id', sa.Integer(), nullable=True))
    op.drop_constraint('pitch_category_fkey', 'pitch', type_='foreignkey')
    op.create_foreign_key(None, 'pitch', 'category', ['category_id'], ['id'])
    op.drop_column('pitch', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('category', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pitch', type_='foreignkey')
    op.create_foreign_key('pitch_category_fkey', 'pitch', 'category', ['category'], ['id'])
    op.drop_column('pitch', 'category_id')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    # ### end Alembic commands ###
