"""Added column content

Revision ID: a93a921d8cee
Revises: 2670f4f91aab
Create Date: 2020-07-11 09:55:40.369040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a93a921d8cee'
down_revision = '2670f4f91aab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('content', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitch', 'content')
    # ### end Alembic commands ###
