"""empty message

Revision ID: b21fe76cb8dc
Revises: 8023ba9ac0f2
Create Date: 2020-07-11 17:01:02.839604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b21fe76cb8dc'
down_revision = '8023ba9ac0f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('posted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitch', 'posted')
    # ### end Alembic commands ###
